set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

set_property PACKAGE_PIN N5 [get_ports rx]
set_property PACKAGE_PIN P17 [get_ports sys_clk]
set_property PACKAGE_PIN R15 [get_ports rst]
set_property PACKAGE_PIN T4 [get_ports tx]

set_property PACKAGE_PIN T5 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN H4 [get_ports front_detector]
set_property PACKAGE_PIN J3 [get_ports back_detector]
set_property PACKAGE_PIN J2 [get_ports left_detector]
set_property PACKAGE_PIN K2 [get_ports right_detector]
set_property IOSTANDARD LVCMOS33 [get_ports back_detector]
set_property IOSTANDARD LVCMOS33 [get_ports front_detector]
set_property IOSTANDARD LVCMOS33 [get_ports left_detector]
set_property IOSTANDARD LVCMOS33 [get_ports right_detector]

set_property PACKAGE_PIN P4 [get_ports reverse]
set_property PACKAGE_PIN P5 [get_ports throttle]
set_property IOSTANDARD LVCMOS33 [get_ports reverse]
set_property IOSTANDARD LVCMOS33 [get_ports throttle]
set_property PACKAGE_PIN P2 [get_ports clutch]
set_property PACKAGE_PIN P3 [get_ports brake]
set_property IOSTANDARD LVCMOS33 [get_ports clutch]
set_property IOSTANDARD LVCMOS33 [get_ports brake]


set_property PACKAGE_PIN V1 [get_ports bu_left]
set_property PACKAGE_PIN R11 [get_ports bu_right]
set_property IOSTANDARD LVCMOS33 [get_ports bu_left]
set_property IOSTANDARD LVCMOS33 [get_ports bu_right]
set_property PACKAGE_PIN N4 [get_ports bu_front]
set_property PACKAGE_PIN V4 [get_ports bu_back]
set_property IOSTANDARD LVCMOS33 [get_ports bu_front]
set_property IOSTANDARD LVCMOS33 [get_ports bu_back]
set_property PACKAGE_PIN R1 [get_ports power_on]
set_property PACKAGE_PIN R17 [get_ports power_off]
set_property IOSTANDARD LVCMOS33 [get_ports power_on]
set_property IOSTANDARD LVCMOS33 [get_ports power_off]

set_property PACKAGE_PIN K1 [get_ports turning_LED[0]]
set_property PACKAGE_PIN K3 [get_ports turning_LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports turning_LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports turning_LED[1]]


set_property PACKAGE_PIN R2 [get_ports place_barrier_signal]
set_property IOSTANDARD LVCMOS33 [get_ports place_barrier_signal]

set_property PACKAGE_PIN M4 [get_ports destroy_barrier_signal]
set_property IOSTANDARD LVCMOS33 [get_ports destroy_barrier_signal]

set_property PACKAGE_PIN U3 [get_ports Mode[2]]
set_property PACKAGE_PIN U2 [get_ports Mode[1]]
set_property PACKAGE_PIN V2 [get_ports Mode[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Mode[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Mode[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Mode[0]]

set_property PACKAGE_PIN G6 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_en[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_out[0]}]
set_property PACKAGE_PIN B4 [get_ports {seg_out[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg_out[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg_out[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg_out[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg_out[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg_out[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg_out[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg_out[0]}]

#//set_property PACKAGE_PIN F6 [get_ports state_semi[1]]
#//set_property IOSTANDARD LVCMOS33 [get_ports state_semi[1]]
#//set_property PACKAGE_PIN G4 [get_ports state_semi[0]]
#//set_property IOSTANDARD LVCMOS33 [get_ports state_semi[0]]

#//set_property PACKAGE_PIN G3 [get_ports next_state_semi[1]]
#//set_property IOSTANDARD LVCMOS33 [get_ports next_state_semi[1]]
#//set_property PACKAGE_PIN J4 [get_ports next_state_semi[0]]
#//set_property IOSTANDARD LVCMOS33 [get_ports next_state_semi[0]]

#//set_property PACKAGE_PIN H5 [get_ports turn_state[2]]
#//set_property PACKAGE_PIN J5 [get_ports turn_state[1]]
#//set_property PACKAGE_PIN K6 [get_ports turn_state[0]]
#//set_property IOSTANDARD LVCMOS33 [get_ports turn_state[2]]
#//set_property IOSTANDARD LVCMOS33 [get_ports turn_state[1]]
#//set_property IOSTANDARD LVCMOS33 [get_ports turn_state[0]]