set_property PACKAGE_PIN P4 [get_ports reverse]
set_property PACKAGE_PIN P5 [get_ports throttle]
set_property IOSTANDARD LVCMOS33 [get_ports reverse]
set_property IOSTANDARD LVCMOS33 [get_ports throttle]
set_property PACKAGE_PIN P2 [get_ports clutch]
set_property IOSTANDARD LVCMOS33 [get_ports clutch]
set_property PACKAGE_PIN V1 [get_ports sw_pON]
set_property PACKAGE_PIN R11 [get_ports sw_pOFF]
set_property IOSTANDARD LVCMOS33 [get_ports sw_pON]
set_property IOSTANDARD LVCMOS33 [get_ports sw_pOFF]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN T5 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN N4 [get_ports state[0]]
set_property IOSTANDARD LVCMOS33 [get_ports state[0]]
set_property PACKAGE_PIN R1 [get_ports state[1]]
set_property IOSTANDARD LVCMOS33 [get_ports state[1]]

set_property PACKAGE_PIN K1 [get_ports power]
set_property IOSTANDARD LVCMOS33 [get_ports power]
set_property PACKAGE_PIN H6 [get_ports next_power]
set_property IOSTANDARD LVCMOS33 [get_ports next_power]
